spring.application.name=2400031984_exp-12Backend
server.port=8080

# MySQL config
spring.datasource.url=jdbc:mysql://localhost:3306/studentdbs?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

